version: '3.7'

services:
  warehouse:
    build: .
    image: warehouse:latest
    container_name: warehouse
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hktvwarehouse
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=hktvwarehouse
    ports:
      - 3306:3306