logging:
  level:
    ROOT: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 0
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8080